const stats = {
  contributors: 13,
  membersData: [
    {
      login: "Abhishek3285",
      id: 168811316,
      node_id: "U_kgDOCg_bNA",
      avatar_url: "https://avatars.githubusercontent.com/u/168811316?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Abhishek3285",
      html_url: "https://github.com/Abhishek3285",
      followers_url: "https://api.github.com/users/Abhishek3285/followers",
      following_url:
        "https://api.github.com/users/Abhishek3285/following{/other_user}",
      gists_url: "https://api.github.com/users/Abhishek3285/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/Abhishek3285/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/Abhishek3285/subscriptions",
      organizations_url: "https://api.github.com/users/Abhishek3285/orgs",
      repos_url: "https://api.github.com/users/Abhishek3285/repos",
      events_url: "https://api.github.com/users/Abhishek3285/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/Abhishek3285/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
    },
  ],
  orgData: {
    login: "SylvenOS",
    id: 289425715,
    node_id: "O_kgDOEUBJMw",
    url: "https://api.github.com/orgs/SylvenOS",
    repos_url: "https://api.github.com/orgs/SylvenOS/repos",
    events_url: "https://api.github.com/orgs/SylvenOS/events",
    hooks_url: "https://api.github.com/orgs/SylvenOS/hooks",
    issues_url: "https://api.github.com/orgs/SylvenOS/issues",
    members_url: "https://api.github.com/orgs/SylvenOS/members{/member}",
    public_members_url:
      "https://api.github.com/orgs/SylvenOS/public_members{/member}",
    avatar_url: "https://avatars.githubusercontent.com/u/289425715?v=4",
    description: "Nexus Point of Tech Community",
    name: "SylvenOS",
    company: null,
    blog: null,
    location: "India",
    email: null,
    twitter_username: "sylvenos_",
    is_verified: false,
    has_organization_projects: true,
    has_repository_projects: true,
    public_repos: 6,
    public_gists: 0,
    followers: 16,
    following: 0,
    html_url: "https://github.com/SylvenOS",
    created_at: "2026-05-31T14:15:29Z",
    updated_at: "2026-07-01T04:18:01Z",
    archived_at: null,
    type: "Organization",
    total_private_repos: 1,
    owned_private_repos: 1,
    private_gists: null,
    disk_usage: null,
    collaborators: null,
    billing_email: null,
    default_repository_permission: null,
    members_can_create_repositories: true,
    two_factor_requirement_enabled: null,
    members_allowed_repository_creation_type: "all",
    members_can_create_public_repositories: true,
    members_can_create_private_repositories: true,
    members_can_create_internal_repositories: false,
    members_can_create_pages: true,
    members_can_fork_private_repositories: false,
    web_commit_signoff_required: false,
    deploy_keys_enabled_for_repositories: false,
    members_can_delete_repositories: true,
    members_can_change_repo_visibility: true,
    members_can_invite_outside_collaborators: true,
    members_can_delete_issues: false,
    display_commenter_full_name_setting_enabled: false,
    readers_can_create_discussions: true,
    members_can_create_teams: true,
    members_can_view_dependency_insights: true,
    default_repository_branch: "main",
    members_can_create_public_pages: true,
    members_can_create_private_pages: true,
    plan: {
      name: "free",
      space: 976562499,
      private_repos: 10000,
      filled_seats: 13,
      seats: 2,
    },
  },
  repos: 6,
};
